<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">

    <title>Lista dos Carros</title>
</head>

<body>
    <style>
    h2 {
        font-size: 18px;
    }
    </style>
    <div class="container">

        <div>
            <nav class="navbar navbar-dark bg-light">
                <a href="/home/">Home</a>
                <a href="/cadastro/">Cadastro</a>
                <a href="/lista/">Lista de Carros</a>
                <a href="/atualizar/">Atualizar Lista</a>
            </nav>
        </div>

        <h1>
            Carros Cadastrados!
        </h1>
        <h2>
            Lista de todos os carros que já foram cadastrados em nosso sistema :)
        </h2>

        <table class="table table-light">
                <thead>
                    <tr>
                        <th scope="col">Id do Carro</th>
                        <th scope="col">Dono</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Ano</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($carros as $key => $carro) {
                        echo '<tr>';
                            echo '<th scope="row">' . $carro['id_carro'] . '</th>';
                            echo '<td>' . $carro['nome_dono'] .'</td>';
                            echo '<td>' . $carro['modelo'] .'</td>';
                            echo '<td>' . $carro['marca'] . '</td>';
                            echo '<td>' . $carro['ano'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
        </table>

    </div>
    
</body>

<script src="/vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</html>