<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">

    <title>Home</title>
</head>

<body>
    <style>
    h2 {
        font-size: 18px;
    }
    </style>
    
    <div class="container">

        <div>
            <nav class="navbar navbar-dark bg-light">
                <a href="/home/">Home</a>
                <a href="/cadastro/">Cadastro</a>
                <a href="/lista/">Lista de Carros</a>
                <a href="/atualizar/">Atualizar Lista</a>
            </nav>
        </div>

        <h1>
        Carros do Murakami, Bem vindo!
        </h1>
        <h2>
        A maior loja de veículos de Blumenau e região ;)
        </h2>
    </div>
    
</body>

<script src="/vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</html>